/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.bancolombia.microservice.getOneEnigmaStep.api;

import co.com.bancolombia.microservice.getOneEnigmaStep.model.JsonApiBodyRequest;
import co.com.bancolombia.microservice.getOneEnigmaStep.model.JsonApiBodyResponseErrors;
import co.com.bancolombia.microservice.getOneEnigmaStep.model.JsonApiBodyResponseSuccess;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-08-15T15:00:12.799-05:00[America/Bogota]")
@Api(value = "getStep", description = "the getStep API")
public interface GetStepApi {

    @ApiOperation(value = "Get one enigma step API", nickname = "getOneEnigmaStep", notes = "", response = JsonApiBodyResponseSuccess.class, tags={ "get-one-enigma-step-api-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Inquery step success", response = JsonApiBodyResponseSuccess.class),
        @ApiResponse(code = 424, message = "Invalid Input. please put correct request", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/getStep",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> getOneEnigmaStep(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody JsonApiBodyRequest body);
}
